import pandas as pd
import numpy as np

# Sub-national distributions for some countries. Electricity denabd us used as key for activity.
germany = {
    "DE4-E":0.14,
    "DE4-W":0.43,
    "DE4-S":0.39,
    "DE4-N":0.04
}
denmark = {
    "DK1":0.59,
    "DK2":0.41
}
sweden = {
    "SE1":0.07,
    "SE2":0.13,
    "SE3":0.62,
    "SE4":0.18
}
norway = {
    "NO1":0.27,
    "NO2":0.27,
    "NO3":0.20,
    "NO4":0.14,
    "NO5":0.12
}

region_map = {
    "FI": "FIN",
    "EL": "GR"
}

region_to_area_map = {
    "AT": "AT_A",
    "BE": "BE_A",
    "BG": "BG_A",
    "CH": "CH_A",
    "CY": "CY_A",
    "CZ": "CZ_A",
    "DE4-W": "DE4-W_A",
    "DE4-E": "DE4-E_A",
    "DE4-S": "DE4-S_A",
    "DE4-N": "DE4-N_A",
    "DK1": "DK1_A",
    "DK2": "DK2_A",
    "EE": "EE_A",
    "ES": "ES_A",
    "FIN": "FIN_A",
    "FR": "FR_A",
    "GR": "GR_A",
    "HR": "HR_A",
    "HU": "HU_A",
    "IE": "IE_A",
    "IT": "IT_A",
    "LT": "LT_A",
    "LU": "LU_A",
    "LV": "LV_A",
    "MT": "MT_A",
    "NL": "NL_A",
    "NO1": "NO1_A",
    "NO2": "NO2_A",
    "NO3": "NO3_A",
    "NO4": "NO4_A",
    "NO5": "NO5_A",
    "PL": "PL_A",
    "PT": "PT_A",
    "RO": "RO_A",
    "SE1": "SE1_A",
    "SE2": "SE2_A",
    "SE3": "SE3_A",
    "SE4": "SE4_A",
    "SI": "SI_A",
    "SK": "SK_A",
}

region_to_industry_map_HT = {
    "AT": "AT_IND-HT",
    "BE": "BE_IND-HT",
    "BG": "BG_IND-HT",
    "CH": "CH_IND-HT",
    "CY": "CY_IND-HT",
    "CZ": "CZ_IND-HT",
    "DE4-W": "DE4-W_IND-HT",
    "DE4-E": "DE4-E_IND-HT",
    "DE4-S": "DE4-S_IND-HT",
    "DE4-N": "DE4-N_IND-HT",
    "DK1": "DK1_IND-HT",
    "DK2": "DK2_IND-HT",
    "EE": "EE_IND-HT",
    "ES": "ES_IND-HT",
    "FIN": "FIN_IND-HT",
    "FR": "FR_IND-HT",
    "GR": "GR_IND-HT",
    "HR": "HR_IND-HT",
    "HU": "HU_IND-HT",
    "IE": "IE_IND-HT",
    "IT": "IT_IND-HT",
    "LT": "LT_IND-HT",
    "LU": "LU_IND-HT",
    "LV": "LV_IND-HT",
    "MT": "MT_IND-HT",
    "NL": "NL_IND-HT",
    "NO1": "NO1_IND-HT",
    "NO2": "NO2_IND-HT",
    "NO3": "NO3_IND-HT",
    "NO4": "NO4_IND-HT",
    "NO5": "NO5_IND-HT",
    "PL": "PL_IND-HT",
    "PT": "PT_IND-HT",
    "RO": "RO_IND-HT",
    "SE1": "SE1_IND-HT",
    "SE2": "SE2_IND-HT",
    "SE3": "SE3_IND-HT",
    "SE4": "SE4_IND-HT",
    "SI": "SI_IND-HT",
    "SK": "SK_IND-HT",
}

region_to_industry_map_MT = {
    "AT": "AT_IND-MT",
    "BE": "BE_IND-MT",
    "BG": "BG_IND-MT",
    "CH": "CH_IND-MT",
    "CY": "CY_IND-MT",
    "CZ": "CZ_IND-MT",
    "DE4-W": "DE4-W_IND-MT",
    "DE4-E": "DE4-E_IND-MT",
    "DE4-S": "DE4-S_IND-MT",
    "DE4-N": "DE4-N_IND-MT",
    "DK1": "DK1_IND-MT",
    "DK2": "DK2_IND-MT",
    "EE": "EE_IND-MT",
    "ES": "ES_IND-MT",
    "FIN": "FIN_IND-MT",
    "FR": "FR_IND-MT",
    "GR": "GR_IND-MT",
    "HR": "HR_IND-MT",
    "HU": "HU_IND-MT",
    "IE": "IE_IND-MT",
    "IT": "IT_IND-MT",
    "LT": "LT_IND-MT",
    "LU": "LU_IND-MT",
    "LV": "LV_IND-MT",
    "MT": "MT_IND-MT",
    "NL": "NL_IND-MT",
    "NO1": "NO1_IND-MT",
    "NO2": "NO2_IND-MT",
    "NO3": "NO3_IND-MT",
    "NO4": "NO4_IND-MT",
    "NO5": "NO5_IND-MT",
    "PL": "PL_IND-MT",
    "PT": "PT_IND-MT",
    "RO": "RO_IND-MT",
    "SE1": "SE1_IND-MT",
    "SE2": "SE2_IND-MT",
    "SE3": "SE3_IND-MT",
    "SE4": "SE4_IND-MT",
    "SI": "SI_IND-MT",
    "SK": "SK_IND-MT",
}